/**//* 38.455.227-PAIVA_GORDILLO,NahuelAlejo-(01-2964) *//**/

#ifndef CUADRADO_H_
#define CUADRADO_H_

#include "Figura.h"

class Cuadrado : public Figura
{
	private:
		double lado;

	public:
		Cuadrado(double lado);
		double area() const;
};
/**ALGO QUE ME PARECE NECESARIO ACLARAR ES QUE NO CREÉ OTROS CONSTRUCTORES
COMO POR EJEMPLO EL CONSTRUCTOR DE UN CUADRADO AL CUAL NO LE PASAN MEDIDA
Y CONSTRUYE POR DEFECTO PORQUE SEGÚN TENGO ENTENDIDO SOLO TENGO QUE LIMITARME
A LOGRAR QUE EL PROYECTO COMPILE BIEN Y SIN ERRORES. POR ENDE ME RESERVO
LA RESOLUCION DE ESTE TIPO DE CONSTRUCTORES.**/




#endif // CUADRADO_H_
